# Generated by Django 3.0.2 on 2020-07-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchDetail',
            fields=[
                ('time', models.BigIntegerField(primary_key=True, serialize=False)),
                ('data', models.TextField()),
            ],
        ),
    ]
