# Generated by Django 3.0.2 on 2020-07-12 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_matchdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='APICallHistory',
            fields=[
                ('time', models.BigIntegerField(primary_key=True, serialize=False)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MatchHistory',
            fields=[
                ('time', models.BigIntegerField(primary_key=True, serialize=False)),
                ('data', models.TextField()),
                ('summoner', models.TextField()),
                ('region', models.TextField()),
            ],
        ),
    ]
