# Generated by Django 3.0.2 on 2020-07-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_apicallhistory_matchhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('time', models.BigIntegerField(primary_key=True, serialize=False)),
                ('key', models.TextField()),
            ],
        ),
    ]
