# Generated by Django 3.0.2 on 2020-07-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_auto_20200712_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='KrogerServiceData',
            fields=[
                ('time', models.BigIntegerField(primary_key=True, serialize=False)),
                ('data', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='apicallhistory',
            name='service',
            field=models.TextField(default='Riot'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='service',
            field=models.TextField(default='Riot'),
        ),
    ]
